language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

matrix:
  allow_failures:
    - php: 5.5

#before_script:
    # - wget http://getcomposer.org/composer.phar
    # - php composer.phar install --dev --no-interaction

script:
    - mkdir -p build/logs
    - phpunit -c travis.phpunit.xml.dist

after_script:
    # - wget https://gist.github.com/satooshi/4750401/raw > travis/ColorCLI.php
    # - wget https://gist.github.com/satooshi/4752226/raw > travis/junit.php
    # - wget https://gist.github.com/satooshi/4958593/raw > travis/pmd.php
    # - wget https://gist.github.com/satooshi/4958909/raw > travis/checkstyle.php
    # - php travis/checkstyle.php
    # - php travis/pmd.php
    # - php travis/junit.php
    - php vendor/bin/coveralls
